/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository of this plugin.
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => TMDBPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  apiReadAccessToken: "",
  insertMode: "cursor",
  newNoteFolder: "",
  defaultMovieTemplate: `---
title: "{{title}}"
year: {{year}}
rating: {{rating}}
genres: [{{genres}}]
director: "{{director}}"
runtime: {{runtime}}
status: "{{status}}"
tagline: "{{tagline}}"
poster: "{{poster_url}}"
---

# {{title}} ({{year}})

> {{tagline}}

{{overview}}

**Director:** {{director}}
**Runtime:** {{runtime}} minutes
**Genres:** {{genres}}
**Rating:** {{rating}}/10
`,
  defaultTVTemplate: `---
title: "{{title}}"
year: {{year}}
rating: {{rating}}
genres: [{{genres}}]
creators: "{{creators}}"
seasons: {{seasons}}
status: "{{status}}"
tagline: "{{tagline}}"
poster: "{{poster_url}}"
---

# {{title}} ({{year}})

> {{tagline}}

{{overview}}

**Created by:** {{creators}}
**Seasons:** {{seasons}}
**Genres:** {{genres}}
**Rating:** {{rating}}/10
`
};
var TMDBSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "TMDB Search Settings" });
    new import_obsidian.Setting(containerEl).setName("API Read Access Token").setDesc(
      "Your TMDB API Read Access Token (Bearer). Get one at themoviedb.org under Settings \u2192 API."
    ).addText((text) => {
      text.setPlaceholder("eyJhbGciOiJIUzI1NiJ9...").setValue(this.plugin.settings.apiReadAccessToken).onChange(async (value) => {
        this.plugin.settings.apiReadAccessToken = value.trim();
        await this.plugin.saveSettings();
      });
      text.inputEl.type = "password";
      text.inputEl.style.width = "100%";
    });
    new import_obsidian.Setting(containerEl).setName("Insert mode").setDesc(
      "Where to put the filled template \u2014 at the cursor position, or in a new note."
    ).addDropdown(
      (drop) => drop.addOption("cursor", "Insert at cursor").addOption("newNote", "Create new note").setValue(this.plugin.settings.insertMode).onChange(async (value) => {
        this.plugin.settings.insertMode = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("New note folder").setDesc(
      'Folder path for new notes (e.g. "Movies"). Leave empty to use vault root.'
    ).addText(
      (text) => text.setPlaceholder("Movies").setValue(this.plugin.settings.newNoteFolder).onChange(async (value) => {
        this.plugin.settings.newNoteFolder = value.trim();
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "Templates" });
    containerEl.createEl("p", {
      text: "Available placeholders: {{title}}, {{year}}, {{overview}}, {{rating}}, {{genres}}, {{poster_url}}, {{status}}, {{tagline}}, {{director}} (movie), {{runtime}} (movie), {{creators}} (TV), {{seasons}} (TV)",
      cls: "setting-item-description"
    });
    new import_obsidian.Setting(containerEl).setName("Movie template").setDesc("Template used when inserting movie data.").addTextArea((area) => {
      area.setValue(this.plugin.settings.defaultMovieTemplate).onChange(async (value) => {
        this.plugin.settings.defaultMovieTemplate = value;
        await this.plugin.saveSettings();
      });
      area.inputEl.rows = 20;
      area.inputEl.style.width = "100%";
      area.inputEl.style.fontFamily = "monospace";
      area.inputEl.style.fontSize = "12px";
    });
    new import_obsidian.Setting(containerEl).setName("TV show template").setDesc("Template used when inserting TV show data.").addTextArea((area) => {
      area.setValue(this.plugin.settings.defaultTVTemplate).onChange(async (value) => {
        this.plugin.settings.defaultTVTemplate = value;
        await this.plugin.saveSettings();
      });
      area.inputEl.rows = 20;
      area.inputEl.style.width = "100%";
      area.inputEl.style.fontFamily = "monospace";
      area.inputEl.style.fontSize = "12px";
    });
  }
};

// src/tmdb.ts
var TMDBError = class extends Error {
  constructor(message, statusCode, isAuthError) {
    super(message);
    this.statusCode = statusCode;
    this.isAuthError = isAuthError;
    this.name = "TMDBError";
  }
};
var TMDBClient = class {
  constructor(token) {
    this.token = token;
    this.baseUrl = "https://api.themoviedb.org/3";
    this.imageBaseUrl = "https://image.tmdb.org/t/p/w500";
  }
  async searchMulti(query) {
    const encoded = encodeURIComponent(query);
    const data = await this.fetchTMDB(
      `/search/multi?query=${encoded}&language=en-US&page=1&include_adult=false`
    );
    return data.results.filter((r) => r.media_type === "movie" || r.media_type === "tv").slice(0, 10);
  }
  async getMovieDetails(id) {
    var _a, _b, _c;
    const data = await this.fetchTMDB(
      `/movie/${id}?append_to_response=credits&language=en-US`
    );
    const director = (_b = (_a = data.credits.crew.find((c) => c.job === "Director")) == null ? void 0 : _a.name) != null ? _b : "";
    const genres = data.genres.map((g) => g.name).join(", ");
    const year = data.release_date ? data.release_date.substring(0, 4) : "";
    return {
      media_type: "movie",
      title: data.title,
      year,
      overview: data.overview,
      rating: this.formatRating(data.vote_average),
      genres,
      poster_url: this.getPosterUrl(data.poster_path),
      status: data.status,
      tagline: (_c = data.tagline) != null ? _c : "",
      director,
      runtime: data.runtime != null ? String(data.runtime) : "",
      creators: "",
      seasons: ""
    };
  }
  async getTVDetails(id) {
    var _a;
    const data = await this.fetchTMDB(
      `/tv/${id}?append_to_response=credits&language=en-US`
    );
    const creators = data.created_by.map((c) => c.name).join(", ");
    const genres = data.genres.map((g) => g.name).join(", ");
    const year = data.first_air_date ? data.first_air_date.substring(0, 4) : "";
    return {
      media_type: "tv",
      title: data.name,
      year,
      overview: data.overview,
      rating: this.formatRating(data.vote_average),
      genres,
      poster_url: this.getPosterUrl(data.poster_path),
      status: data.status,
      tagline: (_a = data.tagline) != null ? _a : "",
      director: "",
      runtime: "",
      creators,
      seasons: String(data.number_of_seasons)
    };
  }
  async fetchTMDB(path) {
    const response = await fetch(`${this.baseUrl}${path}`, {
      headers: {
        Authorization: `Bearer ${this.token}`,
        "Content-Type": "application/json"
      }
    });
    if (!response.ok) {
      const isAuthError = response.status === 401;
      let message = `TMDB API error: ${response.status} ${response.statusText}`;
      try {
        const body = await response.json();
        if (body.status_message) {
          message = body.status_message;
        }
      } catch (e) {
      }
      throw new TMDBError(message, response.status, isAuthError);
    }
    return response.json();
  }
  getPosterUrl(path) {
    if (!path) return "";
    return `${this.imageBaseUrl}${path}`;
  }
  formatRating(avg) {
    return avg.toFixed(1);
  }
};

// src/modal.ts
var import_obsidian2 = require("obsidian");

// src/template.ts
function fillTemplate(template, data) {
  return template.replace(/\{\{(\w+)\}\}/g, (match, key) => {
    if (key in data) {
      return data[key];
    }
    return match;
  });
}

// src/modal.ts
var TMDBSearchModal = class extends import_obsidian2.SuggestModal {
  constructor(app, client, settings) {
    super(app);
    this.debounceTimer = null;
    this.DEBOUNCE_MS = 400;
    this.client = client;
    this.settings = settings;
    this.setPlaceholder("Search for a movie or TV show...");
  }
  getSuggestions(query) {
    return new Promise((resolve) => {
      if (this.debounceTimer !== null) {
        window.clearTimeout(this.debounceTimer);
      }
      if (!query.trim()) {
        resolve([]);
        return;
      }
      this.debounceTimer = window.setTimeout(async () => {
        try {
          const results = await this.client.searchMulti(query);
          resolve(results);
        } catch (e) {
          this.handleError(e);
          resolve([]);
        }
      }, this.DEBOUNCE_MS);
    });
  }
  renderSuggestion(result, el) {
    const { title, year } = this.getDisplayInfo(result);
    const isMovie = result.media_type === "movie";
    const item = el.createDiv({ cls: "tmdb-result-item" });
    const main = item.createDiv({ cls: "tmdb-result-main" });
    main.createSpan({
      cls: "tmdb-result-title",
      text: year ? `${title} (${year})` : title
    });
    main.createSpan({
      cls: `tmdb-result-badge ${isMovie ? "tmdb-badge-movie" : "tmdb-badge-tv"}`,
      text: isMovie ? "Movie" : "TV"
    });
    if (result.overview) {
      item.createDiv({
        cls: "tmdb-result-overview",
        text: result.overview
      });
    }
  }
  async onChooseSuggestion(result, _evt) {
    try {
      const isMovie = result.media_type === "movie";
      const mediaData = isMovie ? await this.client.getMovieDetails(result.id) : await this.client.getTVDetails(result.id);
      const template = isMovie ? this.settings.defaultMovieTemplate : this.settings.defaultTVTemplate;
      const filled = fillTemplate(template, mediaData);
      if (this.settings.insertMode === "cursor") {
        this.insertAtCursor(filled);
      } else {
        await this.createNewNote(filled, mediaData);
      }
      new import_obsidian2.Notice(`Added: ${mediaData.title}`);
    } catch (e) {
      this.handleError(e);
    }
  }
  insertAtCursor(content) {
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian2.MarkdownView);
    if (!activeView) {
      new import_obsidian2.Notice("No active markdown editor found.");
      return;
    }
    activeView.editor.replaceSelection(content);
  }
  async createNewNote(content, data) {
    const sanitized = data.title.replace(/[\\/:*?"<>|]/g, "-");
    const baseName = data.year ? `${sanitized} (${data.year})` : sanitized;
    const folder = this.settings.newNoteFolder ? this.settings.newNoteFolder.replace(/\/$/, "") : "";
    const buildPath = (suffix) => {
      const name = suffix ? `${baseName} ${suffix}` : baseName;
      return folder ? `${folder}/${name}.md` : `${name}.md`;
    };
    let path = buildPath("");
    let counter = 2;
    while (this.app.vault.getAbstractFileByPath(path) instanceof import_obsidian2.TFile && counter <= 99) {
      path = buildPath(String(counter));
      counter++;
    }
    const file = await this.app.vault.create(path, content);
    await this.app.workspace.getLeaf(false).openFile(file);
  }
  getDisplayInfo(result) {
    var _a, _b, _c, _d;
    const title = result.media_type === "movie" ? (_b = (_a = result.title) != null ? _a : result.name) != null ? _b : "Unknown" : (_d = (_c = result.name) != null ? _c : result.title) != null ? _d : "Unknown";
    const dateStr = result.media_type === "movie" ? result.release_date : result.first_air_date;
    const year = dateStr ? dateStr.substring(0, 4) : "";
    return { title, year };
  }
  handleError(error) {
    if (error instanceof TMDBError) {
      if (error.isAuthError) {
        new import_obsidian2.Notice(
          "TMDB: Invalid API token. Check your settings."
        );
      } else if (error.statusCode === 429) {
        new import_obsidian2.Notice("TMDB: Too many requests. Please wait a moment.");
      } else {
        new import_obsidian2.Notice(`TMDB error: ${error.message}`);
      }
    } else if (error instanceof TypeError) {
      new import_obsidian2.Notice("TMDB: Network error. Check your connection.");
    } else {
      new import_obsidian2.Notice("TMDB: An unexpected error occurred.");
    }
  }
};

// src/main.ts
var TMDBPlugin = class extends import_obsidian3.Plugin {
  async onload() {
    await this.loadSettings();
    this.initializeClient();
    this.addRibbonIcon("film", "Search TMDB", () => {
      this.openSearchModal();
    });
    this.addCommand({
      id: "tmdb-search",
      name: "Search TMDB for movie or TV show",
      callback: () => {
        this.openSearchModal();
      }
    });
    this.addSettingTab(new TMDBSettingTab(this.app, this));
  }
  async onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      await this.loadData()
    );
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.initializeClient();
  }
  initializeClient() {
    this.client = new TMDBClient(this.settings.apiReadAccessToken);
  }
  openSearchModal() {
    if (!this.settings.apiReadAccessToken) {
      new import_obsidian3.Notice(
        "TMDB: Please set your API Read Access Token in settings."
      );
      return;
    }
    new TMDBSearchModal(this.app, this.client, this.settings).open();
  }
};
